$kind: http-request
name: "Organization Settings: Get by Organization Id"
url: "{{baseUrl}}/api/organization/organization-settings/organization/3"
method: GET
headers:
  Authorization: Bearer {{accessToken}}
auth:
  type: bearer
order: 35000
