$kind: http-request
name: "Organization Settings: Update"
url: "{{baseUrl}}/api/organization/organization-settings/1"
method: PUT
headers:
  Authorization: Bearer {{accessToken}}
  Content-Type: application/json
body:
  type: json
  content: |-
    {
      "organizationId": 1,

      "locationShortName": "OXYGEN",
      "centerName": "OXYGEN",
      "hospitalType": "CLINIC",
      "facilityId": "90",

      "version": "",
      "versionDate": null,
      "isPHC": false,

      "financialStartDate": "2009-01-01T00:00:00",
      "financialEndDate": "2009-12-31T00:00:00",

      "vatEnable": false,
      "vatStartDate": null,
      "vatNumber": "",
      "clearVat": false,

      "ptNumber": 1,
      "ptStart": "0000",
      "ptPrefix": "OM",
      "dPatReg": false,
      "dpStartNo": "",
      "dpPrefix": "",
      "patFolderPath": "",
      "nextOfKin": false,
      "patEmailRequired": false,

      "opBill": false,
      "opBillCashPrefix": "",
      "opBillCreditPrefix": "",
      "opBillCashStart": "",
      "opBillCreditStart": "",
      "opBillAutoPost": false,
      "dpBillStart": "",
      "dpBillPrefix": "",
      "receiptPrefix": "",
      "separateBillNo": false,
      "billMargin": false,
      "collectCash": false,
      "coInsurance": false,
      "billProc": "",
      "receiptProc": "",
      "claimSubCoder": false,
      "opDirectPrint": false,
      "opPrintFormat": null,
      "printHeader": false,
      "productExpiryDays": null,

      "onlyLab": false,
      "labNo": "",
      "radNo": "",
      "autoLabNo": false,
      "noRadLab": false,
      "labHeader": false,
      "lbAutoResult": false,
      "externalLab": false,
      "externalLabCash": false,
      "labIntegration": "",
      "labRadBillLoc": null,
      "hl7Dir": "",
      "hl7Pacs": false,
      "hl7RepDir": "",
      "radWebUrl": "",

      "emrPath": "",
      "emrPassword": "",
      "emrUser": "",
      "emrLog": false,
      "hideEmrDate": false,
      "docOrder": false,
      "dChartPath": "",
      "adb4Approval": false,
      "icdExpiryDate": null,

      "haadUserId": "",
      "haadPassword": "",
      "haUrl": "",
      "healthAuth": "",
      "eClaimPath": "",

      "malaffiSendApp": "",
      "malaffiSendFac": "",
      "malaffiUniversalId": "",
      "malaffiPath": "",
      "malaffiUrl": "",
      "malaffiStatus": false,
      "malaffiDate": null,
      "malaffiFutureAppt": false,

      "serverIp": "",
      "fileServerIp": "",
      "storageDb": false,
      "dbName": "",
      "dbUserId": "",
      "dbPassword": "",
      "archDbName": "",
      "fsDbName": "",
      "logDbName": "",
      "tokenDbName": "",
      "callCenterDb": "",
      "bcpPort": "",
      "bcpName": "",
      "smsPath": "",
      "phDsn": "",
      "pharmaPrintIp": "",
      "xmlPath": "",
      "externalFilePath": "",
      "externalPhPath": "",
      "downloadDir": "",
      "templatePath": "",
      "defaultFileExtension": "",
      "covidCsvPath": "",

      "apptColor": false,
      "apptColSize": null,
      "allowApptDoc": false,
      "chatDisabled": false,
      "consultByDept": false,
      "ramadanTime": false,
      "multiAppt": false,
      "actTime": false,
      "dayOff": "",

      "prefixAfterNumber": false,
      "flagActDone": false,
      "didUKnow": false,
      "homeCare": false,
      "skinCare": false,
      "ownPharmacy": false,
      "referral": false,
      "sigPadDevice": "",
      "initConsent": false,
      "sticByBarcode": false,
      "dmcDuration": null,
      "lQty": false
    }
auth:
  type: noauth
order: 37000
