$kind: http-request
url: "{{baseUrl}}/api/organization/user-theme-settings"
method: PUT
headers:
  Authorization: Bearer {{accessToken}}
body:
  type: json
  content: |-
    {
      "userId": 1,
      "organizationId": 1,
      "theme": "light",
      "languagePreference": "ar",
      "isActive": true
    }
auth:
  type: noauth
order: 4000
